development:
  sessions:
    default:
      hosts: 
        - localhost
      database: yheemeyer

test:
  sessions:
    default:
      hosts: 
        - localhost
      database: yheemeyer-test

production:
  sessions:
    default:
      hosts: 
        - localhost
      database: yheemeyer
